/* 06_english_aliases.sql — EN/romanized alias สำหรับ store matching (kind='english')
   auto-generated จาก domain/english-aliases.ts (961 rows / 181 ร้าน). idempotent. */

DELETE FROM dbo.M_MatchAlias WHERE kind = N'english';

INSERT INTO dbo.M_MatchAlias (kind, alias, canonical, note) VALUES
(N'english', N'chaloemthai', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chaloem thai', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chalermthai', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chalerm thai', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chaloemthai department store', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chalermthai department store', N'บริษัท เฉลิมไทย ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'chaiwiwat', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chai wiwat', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chaiwiwat s.p.', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chaiwiwat sp', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chaiwiwat s p', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chaivivat', N'บริษัท ชัยวิวัฒน์ เอส.พี.จำกัด', N'auto-en'),
(N'english', N'chumphon ocean', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'chumphon ocean group', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'chumphonocean', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'chumporn ocean', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'chumphon ocean grup', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'ocean chumphon', N'บริษัท ชุมพรโอเชี่ยนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'chiang mai cosmetics', N'บริษัท เชียงใหม่ คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'chiangmai cosmetics', N'บริษัท เชียงใหม่ คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'chiang mai cosmetic', N'บริษัท เชียงใหม่ คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'cm cosmetics', N'บริษัท เชียงใหม่ คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'chiangmaicosmetics', N'บริษัท เชียงใหม่ คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'chok chai', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chokchai', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chock chai', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chokchai', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chokchaicompany', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chok chai company', N'บริษัท โชคชัย จำกัด', N'auto-en'),
(N'english', N'chok na thawi', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'choknathawi', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'chok na thawi phoemsap', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'choknathaviphermsap', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'chok nathawi', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'chok na thawi permsap', N'บริษัท โชคนาทวีเพิ่มทรัพย์ จำกัด', N'auto-en'),
(N'english', N'c.d. sungai kolok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'cd sungai kolok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'cd sungaikolok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'c.d. su-ngai kolok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'cd su ngai kolok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'cd sungai golok', N'บริษัท ซี.ดี.สุไหงโกลก', N'auto-en'),
(N'english', N'sun heng plaza', N'บริษัท ซุ่นเฮงพลาซ่า จำกัด', N'auto-en'),
(N'english', N'sunheng plaza', N'บริษัท ซุ่นเฮงพลาซ่า จำกัด', N'auto-en'),
(N'english', N'soon heng plaza', N'บริษัท ซุ่นเฮงพลาซ่า จำกัด', N'auto-en'),
(N'english', N'sunhengplaza', N'บริษัท ซุ่นเฮงพลาซ่า จำกัด', N'auto-en'),
(N'english', N'sun heng', N'บริษัท ซุ่นเฮงพลาซ่า จำกัด', N'auto-en'),
(N'english', N'super cheap', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'supercheap', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'super cheap', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'supercheep', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'super cheep', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'supercheap company', N'บริษัท ซุปเปอร์ชีป จำกัด', N'auto-en'),
(N'english', N'sentosa', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'centosa', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'sentosa', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'santosa', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'sentosa company', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'centosa company', N'บริษัท เซ็นโทซ่า จำกัด', N'auto-en'),
(N'english', N'safe minimart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'safe mini mart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'safeminimart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'save minimart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'save mini mart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'saveminimart', N'บริษัท เซฟ มินิมาร์ท จำกัด', N'auto-en'),
(N'english', N'talad 3 prathet', N'บริษัท ตลาด3ประเทศ จำกัด', N'auto-en'),
(N'english', N'talat sam prathet', N'บริษัท ตลาด3ประเทศ จำกัด', N'auto-en'),
(N'english', N'talad 3 country', N'บริษัท ตลาด3ประเทศ จำกัด', N'auto-en'),
(N'english', N'3 country market', N'บริษัท ตลาด3ประเทศ จำกัด', N'auto-en'),
(N'english', N'talad3prathet', N'บริษัท ตลาด3ประเทศ จำกัด', N'auto-en'),
(N'english', N'tawan ok kha plik', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'tawanok retail', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'tawan ok retail', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'tawanokkhaplik', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'tawan-ok retail', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'tawanok', N'บริษัท ตะวันออกค้าปลีก จำกัด', N'auto-en'),
(N'english', N'thawikit plaza', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thaweekit plaza buriram', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thawikit plaza buriram', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thaweekitplaza', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thawi kit plaza', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thawikit buriram', N'บริษัท ทวีกิจพลาซ่าบุรีรัมย์ จำกัด', N'auto-en'),
(N'english', N'thawicharoen', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'thawi charoen', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'thaweecharoen 2502', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'thawicharoen 2502', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'thawi charoen 2502', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'thaweecharoen', N'บริษัท ทวีเจริญ 2502 จำกัด', N'auto-en'),
(N'english', N'toffee wholesale', N'บริษัท ท็อฟฟี่โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'toffee', N'บริษัท ท็อฟฟี่โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'toffee holsell', N'บริษัท ท็อฟฟี่โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'toffeewholesale', N'บริษัท ท็อฟฟี่โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'toffee holesale', N'บริษัท ท็อฟฟี่โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'tmk kanchanaburi', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N'tmk kanchanaburi trading', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N'tmk trading', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N'tmkkanchanaburi', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N't m k kanchanaburi', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N'tmk kanchana buri', N'บริษัท ทีเอ็มเค กาญจนบุรี เทรดดิ้ง', N'auto-en'),
(N'english', N'thaikhun superstore', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'thai khun superstore', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'taikhun superstore', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'thaikhun super store', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'thaikhunsuperstore', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'thaikun superstore', N'บริษัท ไทคูณซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'thai somboon super', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thaisomboon super', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thai somboon', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thaisomboonsuper', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thai somboon superstore', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thaisombun super', N'บริษัท ไทยสมบูรณ์ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'thanakrit sutthikan', N'บริษัท ธนกฤต สุทธิกานต์ จำกัด', N'auto-en'),
(N'english', N'thanakrit', N'บริษัท ธนกฤต สุทธิกานต์ จำกัด', N'auto-en'),
(N'english', N'tanakrit suttikan', N'บริษัท ธนกฤต สุทธิกานต์ จำกัด', N'auto-en'),
(N'english', N'thanakritsutthikan', N'บริษัท ธนกฤต สุทธิกานต์ จำกัด', N'auto-en'),
(N'english', N'thanakrit sutthikant', N'บริษัท ธนกฤต สุทธิกานต์ จำกัด', N'auto-en'),
(N'english', N'thanapiriya', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'thana piriya', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'thanapiriya', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'tanapiriya', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'thanapiriya pcl', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'thana piriya', N'บริษัท ธนพิริยะ จำกัด (มหาชน)', N'auto-en'),
(N'english', N'nara hypermart', N'บริษัท นรา ไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'narahypermart', N'บริษัท นรา ไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'nara hyper mart', N'บริษัท นรา ไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'nara', N'บริษัท นรา ไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'นราไฮเปอร์มาร์ท', N'บริษัท นรา ไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'nicksland trading', N'บริษัท นิคส์แลนด์ เทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'nicksland', N'บริษัท นิคส์แลนด์ เทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'nicks land', N'บริษัท นิคส์แลนด์ เทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'nickland trading', N'บริษัท นิคส์แลนด์ เทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'nix land', N'บริษัท นิคส์แลนด์ เทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'new top world', N'บริษัท นิวท็อปเวิลด์ (2000) จำกัด', N'auto-en'),
(N'english', N'newtopworld', N'บริษัท นิวท็อปเวิลด์ (2000) จำกัด', N'auto-en'),
(N'english', N'new topworld', N'บริษัท นิวท็อปเวิลด์ (2000) จำกัด', N'auto-en'),
(N'english', N'new top world 2000', N'บริษัท นิวท็อปเวิลด์ (2000) จำกัด', N'auto-en'),
(N'english', N'newtopworld 2000', N'บริษัท นิวท็อปเวิลด์ (2000) จำกัด', N'auto-en'),
(N'english', N'blue shop mahanakhon', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'blueshop mahanakhon', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'blue shop', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'blueshop', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'blue shop mahanakorn', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'blueshopmahanakhon', N'บริษัท บลูช็อปมหานคร จำกัด', N'auto-en'),
(N'english', N'bangbon super center', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'bangbon supercenter', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'bang bon super center', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'bangbon', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'bangbonsupercenter', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'bangbon super', N'บริษัท บางบอนซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'big cat mart', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'bigcat mart', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'big cat', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'bigcat', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'bigcatmart', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'big cat market', N'บริษัท บิ๊กแคท มาร์ท จำกัด', N'auto-en'),
(N'english', N'big song superstore', N'บริษัท บิ๊กซ้ง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'bigsong', N'บริษัท บิ๊กซ้ง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'big song', N'บริษัท บิ๊กซ้ง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'big zong superstore', N'บริษัท บิ๊กซ้ง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'bigsong superstore', N'บริษัท บิ๊กซ้ง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'big suea super store', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'big sua superstore', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'big suea', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'bigsua', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'bigsuea super store', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'big tiger super store', N'บริษัท บิ๊กเสือซูเปอร์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'better off', N'บริษัท เบทเทอร์ ออฟ จำกัด', N'auto-en'),
(N'english', N'betteroff', N'บริษัท เบทเทอร์ ออฟ จำกัด', N'auto-en'),
(N'english', N'better', N'บริษัท เบทเทอร์ ออฟ จำกัด', N'auto-en'),
(N'english', N'better of', N'บริษัท เบทเทอร์ ออฟ จำกัด', N'auto-en'),
(N'english', N'better-off', N'บริษัท เบทเทอร์ ออฟ จำกัด', N'auto-en'),
(N'english', N'porntawee donkhom distribution', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'porntawee donkhom', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'phonthawi donkhom', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'porntawee', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'porntaweedonkhom distribution', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'porn tawee don khom', N'บริษัท พรทวีดอนขม ดิสทริบิวชั่น จำกัด', N'auto-en'),
(N'english', N'pp supercenter', N'บริษัท พี พี ซูเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'p p supercenter', N'บริษัท พี พี ซูเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'ppsupercenter', N'บริษัท พี พี ซูเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'pp super center', N'บริษัท พี พี ซูเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'pp', N'บริษัท พี พี ซูเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'py kitsiri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'p.y. kitsiri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'py kit siri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'kitsiri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'pykitsiri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'py kijsiri', N'บริษัท พี.วาย.กิจศิริ จำกัด', N'auto-en'),
(N'english', N'phrae charoensin trading', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'prae charoensin trading', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'phrae charoensin', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'praecharoensin', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'phrae charoen sin trading', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'charoensin trading', N'บริษัท แพร่เจริญสินเทรดดิ้ง จำกัด', N'auto-en'),
(N'english', N'farm mart modern trade', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'farmmart modern trade', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'farm mart', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'farmmart', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'farmmartmoderntrade', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'farm mart moderntrade', N'บริษัท ฟาร์มมาร์ทโมเดิร์นเทรด จำกัด', N'auto-en'),
(N'english', N'five star marco', N'บริษัท ไฟว์สตาร์มาร์โค จำกัด', N'auto-en'),
(N'english', N'fivestar marco', N'บริษัท ไฟว์สตาร์มาร์โค จำกัด', N'auto-en'),
(N'english', N'fivestarmarco', N'บริษัท ไฟว์สตาร์มาร์โค จำกัด', N'auto-en'),
(N'english', N'5 star marco', N'บริษัท ไฟว์สตาร์มาร์โค จำกัด', N'auto-en'),
(N'english', N'five star marko', N'บริษัท ไฟว์สตาร์มาร์โค จำกัด', N'auto-en'),
(N'english', N'phinyo kankha', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'pinyo kanka', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'phinyo kan kha jelang', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'jelang', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'je lang', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'phinyokankha 2018', N'บริษัท ภิญโญการค้า(เจ๊ลั้ง)2018 จำกัด', N'auto-en'),
(N'english', N'phiron niwet super store', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'piron niwet superstore', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'phiron niwet', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'pironniwet', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'phironniwet superstore', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'phiron nivej super store', N'บริษัท ภิรณ์นิเวศน์ ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'mother marketing', N'บริษัท มาเธอร์ มาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'mothermarketing', N'บริษัท มาเธอร์ มาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'mother', N'บริษัท มาเธอร์ มาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'mathoe marketing', N'บริษัท มาเธอร์ มาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'mother marketting', N'บริษัท มาเธอร์ มาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'mali superstore', N'บริษัท มาลี ซูเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'malee superstore', N'บริษัท มาลี ซูเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'mali super store', N'บริษัท มาลี ซูเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'malisuperstore', N'บริษัท มาลี ซูเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'mali', N'บริษัท มาลี ซูเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'mukda market', N'บริษัท มุกดา มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'mukdamarket', N'บริษัท มุกดา มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'mukda mart', N'บริษัท มุกดา มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'mukda', N'บริษัท มุกดา มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'mookda market', N'บริษัท มุกดา มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'may laomongseng', N'บริษัท เมย์ (เล้าม่งเส็ง) จำกัด', N'auto-en'),
(N'english', N'may', N'บริษัท เมย์ (เล้าม่งเส็ง) จำกัด', N'auto-en'),
(N'english', N'lao mong seng', N'บริษัท เมย์ (เล้าม่งเส็ง) จำกัด', N'auto-en'),
(N'english', N'laomongseng', N'บริษัท เมย์ (เล้าม่งเส็ง) จำกัด', N'auto-en'),
(N'english', N'may lao mong seng', N'บริษัท เมย์ (เล้าม่งเส็ง) จำกัด', N'auto-en'),
(N'english', N'si ngam', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sringam', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sri ngam', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'si ngam department store', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sringam sapphasin', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sri ngam sapphasinkha', N'บริษัท ศรีงามสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'si samai', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'sri samai', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'srisamai', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'si samai khasong', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'sri samai wholesale', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'srisamai kasong', N'บริษัท ศรีสมัยค้าส่ง จำกัด', N'auto-en'),
(N'english', N'diana', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'diana complex', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'dianacomplex', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'diana shopping', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'sun kan kha diana', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'diana center', N'บริษัท ศูนย์การค้าไดอาน่าคอมเพล็กซ์', N'auto-en'),
(N'english', N'so supermarket', N'บริษัท ส.ซุปเปอร์มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N's supermarket', N'บริษัท ส.ซุปเปอร์มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'sor supermarket', N'บริษัท ส.ซุปเปอร์มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N'ssupermarket', N'บริษัท ส.ซุปเปอร์มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N's. supermarket', N'บริษัท ส.ซุปเปอร์มาร์เก็ต จำกัด', N'auto-en'),
(N'english', N's thaweekit', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N'big one', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N'bigone', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N's thawikit big one', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N'so thawikit', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N's thaweekij bigone', N'บริษัท ส.ทวีกิจ (บิ๊กวัน) จำกัด', N'auto-en'),
(N'english', N's l holsale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'sl wholesale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N's.l. wholesale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'sl holsale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N's l wholesale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'slwholesale', N'บริษัท ส.ล.โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'sakon thana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'sakonthana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'sakol thana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'sakolthana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'sakon tana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'sakontana', N'บริษัท สกลธนา จำกัด', N'auto-en'),
(N'english', N'spring land supermarket', N'บริษัท สปริงแลนด์ ซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'springland', N'บริษัท สปริงแลนด์ ซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'spring land', N'บริษัท สปริงแลนด์ ซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'springland supermarket', N'บริษัท สปริงแลนด์ ซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'springland super', N'บริษัท สปริงแลนด์ ซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'somsak', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'somsak wholesale', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'somsak holsale', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'somsak holsales', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'somsak hollsales', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'somsak holesale', N'บริษัท สมศักดิ์ โฮลล์เซลส์ จำกัด', N'auto-en'),
(N'english', N'som sawat', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'somsawat', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'somsawat department store', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'som sawat department store', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'somsawat dept store', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'somsawatdee', N'บริษัท สมสวัสดิ์ดีพาร์ทเมนท์สโตร์ จำกัด', N'auto-en'),
(N'english', N'sarawan', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sarawan 2015', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sarawal', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sarawal 2015', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sarawan2015', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sarawal2015', N'บริษัท สราวัลย์ 2015 จำกัด', N'auto-en'),
(N'english', N'sahathai super', N'บริษัท สหไทยซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'saha thai super', N'บริษัท สหไทยซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'sahathaisuper', N'บริษัท สหไทยซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'sahathai', N'บริษัท สหไทยซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'saha thai', N'บริษัท สหไทยซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'sahathai department store', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'saha thai department store', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'sahathai dept store', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'sahathai', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'saha thai', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'sahathaidepartmentstore', N'บริษัท สหไทยดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'saha saeng chai', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'sahasaengchai', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'saha sangchai marketing', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'sahasaengchai marketing', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'saha saengchai', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'sahasangchai', N'บริษัท สหแสงชัยมาร์เก็ตติ้ง จำกัด', N'auto-en'),
(N'english', N'song saeng', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'songsaeng', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'song saeng superstore', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'songsaeng super', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'song sang superstore', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'songsang', N'บริษัท ส่องแสง ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'sin 2000', N'บริษัท สิน 2000 จำกัด', N'auto-en'),
(N'english', N'sin2000', N'บริษัท สิน 2000 จำกัด', N'auto-en'),
(N'english', N'sin two thousand', N'บริษัท สิน 2000 จำกัด', N'auto-en'),
(N'english', N'sin 2000 co', N'บริษัท สิน 2000 จำกัด', N'auto-en'),
(N'english', N'sin2000', N'บริษัท สิน 2000 จำกัด', N'auto-en'),
(N'english', N'sin kiat thani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'sinkiatthani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'sin kiatthani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'sinkiat thani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'sin kiet thani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'sinkiettani', N'บริษัท สินเกียรติธานี จำกัด', N'auto-en'),
(N'english', N'siriban shopping center', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'siriban', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'siri ban shopping center', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'siribanshopping', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'siriban shopping centre', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'siribun shopping center', N'บริษัท สิริบรรณช้อปปิ้งเซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'saeng thai phrae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'saengthai phrae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'saeng thai prae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'saengthaiphrae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'sang thai phrae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'saengthai prae', N'บริษัท แสงไทยแพร่ จำกัด', N'auto-en'),
(N'english', N'sahathai department store', N'บริษัท ห้างสหไทยสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sahathai sapphasinkha', N'บริษัท ห้างสหไทยสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sahathai', N'บริษัท ห้างสหไทยสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'saha thai department', N'บริษัท ห้างสหไทยสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'sahathaisapphasinka', N'บริษัท ห้างสหไทยสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'ueng seng heng', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'uengsengheng', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'eng seng heng', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'engsengheng', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'ung seng heng', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'อึ้งเซ้งเฮง', N'บริษัท อึ้งเซ้งเฮง (1994) จำกัด', N'auto-en'),
(N'english', N'uttaradit st trading', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'uttaradit s.t. trading', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'uttaradit trading', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'uttaradit st', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'uttaraditsttrading', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'utaradit trading', N'บริษัท อุตรดิตถ์ เอส.ที. เทรดดิ้ง จ', N'auto-en'),
(N'english', N'ubon dmart', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'ubon d-mart', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'ubon dee mart', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'ubondmart', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'ubol dmart', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'อุบลดีมาร์ท', N'บริษัท อุบลดีมาร์ท (2001) จำกัด', N'auto-en'),
(N'english', N'ekkaphap inter electric', N'บริษัท เอกภาพ อินเตอร์อิเลคตริค จำกัด', N'auto-en'),
(N'english', N'ekapap inter electric', N'บริษัท เอกภาพ อินเตอร์อิเลคตริค จำกัด', N'auto-en'),
(N'english', N'ekkaphap', N'บริษัท เอกภาพ อินเตอร์อิเลคตริค จำกัด', N'auto-en'),
(N'english', N'ekkaphapinterelectric', N'บริษัท เอกภาพ อินเตอร์อิเลคตริค จำกัด', N'auto-en'),
(N'english', N'ekkaphap interelectric', N'บริษัท เอกภาพ อินเตอร์อิเลคตริค จำกัด', N'auto-en'),
(N'english', N'ekkapap super supply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekapap super supply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekkaphap super supply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekkapapsupersupply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekapap supply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekkapap supersupply', N'บริษัท เอกภาพซุปเปอร์ซัพพลาย จำกัด', N'auto-en'),
(N'english', N'ekkapap homemart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekapap homemart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekkapap home mart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekkaphap homemart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekkapaphomemart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekapap home mart', N'บริษัท เอกภาพโฮมมาร์ท จำกัด', N'auto-en'),
(N'english', N'ekworanan', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'ek woranan', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'ekkaworanan', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'ekvoranan', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'ek voranan', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'เอกวรนันท์', N'บริษัท เอกวรนันท์ จำกัด', N'auto-en'),
(N'english', N'nrk and', N'บริษัท เอ็น.อาร์.เค.แอนด์', N'auto-en'),
(N'english', N'n r k and', N'บริษัท เอ็น.อาร์.เค.แอนด์', N'auto-en'),
(N'english', N'nrk', N'บริษัท เอ็น.อาร์.เค.แอนด์', N'auto-en'),
(N'english', N'n.r.k.', N'บริษัท เอ็น.อาร์.เค.แอนด์', N'auto-en'),
(N'english', N'nrkand', N'บริษัท เอ็น.อาร์.เค.แอนด์', N'auto-en'),
(N'english', N'mm sukhothai', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'mmsukhothai', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'm m sukhothai', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'mm sukothai', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'mm sukhotai', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'เอ็มเอ็ม สุโขทัย', N'บริษัท เอ็มเอ็ม สุโขทัย', N'auto-en'),
(N'english', N'skb wholesale', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N'skb holesale', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N'skb holsel', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N's k b wholesale', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N'skbwholesale', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N'skb holzel', N'บริษัท เอส เค บี โฮลเซล จำกัด', N'auto-en'),
(N'english', N'sr supermart', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N's.r. supermart', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'sr super mart', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N's r supermart', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'srsupermart', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'sr supermarket', N'บริษัท เอส.อาร์. ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'ocean superstore', N'บริษัท โอเชียนซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'ocean super store', N'บริษัท โอเชียนซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'oceansuperstore', N'บริษัท โอเชียนซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'ocean', N'บริษัท โอเชียนซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'ocean super', N'บริษัท โอเชียนซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'odeon southern center', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'odian southern center', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'odeon southern centre', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'odeonsoutherncenter', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'odian southern centre', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'odeon south center', N'บริษัท โอเดียนเซาท์เทิร์นเซ็นเตอร์', N'auto-en'),
(N'english', N'hokkee supermart', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'hok kee supermart', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'hokki supermart', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'hokkee super mart', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'hokkeesupermart', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'hokkee supermarket', N'บริษัท ฮกกี่ซุปเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'tt business management', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N'tt business', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N'tt business managment', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N'ttbusinessmanagement', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N't t business management', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N'tt biz management', N'บริษัททีที บิซิเนส แมเนจเมนท์ จำกัด', N'auto-en'),
(N'english', N'betong minimart', N'เบตงมินิมาร์ท', N'auto-en'),
(N'english', N'betong mini mart', N'เบตงมินิมาร์ท', N'auto-en'),
(N'english', N'betongminimart', N'เบตงมินิมาร์ท', N'auto-en'),
(N'english', N'betong', N'เบตงมินิมาร์ท', N'auto-en'),
(N'english', N'betong mini-mart', N'เบตงมินิมาร์ท', N'auto-en'),
(N'english', N'thahan akat', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'thahanakat', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'thahan akas', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'air force store', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'rtaf store', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'thahan agard', N'ร้านค้า ทหารอากาศ ( ท.อ.)', N'auto-en'),
(N'english', N'sahakorn krungthep', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'sahakorn bangkok', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'sahakon krungthep', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'bangkok cooperative', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'sahakornkrungthep', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'sahakorn krung thep', N'ร้านสหกรณ์กรุงเทพ จำกัด', N'auto-en'),
(N'english', N'lertfa minimart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'loetfa minimart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'lert fa minimart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'lertfa mini mart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'lertfaminimart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'lerdfa minimart', N'เลิศฟ้ามินิมาร์ท', N'auto-en'),
(N'english', N'surat thani cooperative', N'สหกรณ์สุราษฎร์ธานี จำกัด', N'auto-en'),
(N'english', N'suratthani cooperative', N'สหกรณ์สุราษฎร์ธานี จำกัด', N'auto-en'),
(N'english', N'surat cooperative', N'สหกรณ์สุราษฎร์ธานี จำกัด', N'auto-en'),
(N'english', N'sahakorn surat thani', N'สหกรณ์สุราษฎร์ธานี จำกัด', N'auto-en'),
(N'english', N'suratthani coop', N'สหกรณ์สุราษฎร์ธานี จำกัด', N'auto-en'),
(N'english', N'krabi benjamin', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'krabi benchamin', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'krabi benjamint', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'krabibenjamin', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'krabi benchamint', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'กระบี่เบญจมินทร์', N'ห้างหุ้นส่วนจำกัด กระบี่เบญจมินทร์', N'auto-en'),
(N'english', N'big c', N'BIG C', N'auto-en'),
(N'english', N'bigc', N'BIG C', N'auto-en'),
(N'english', N'big-c', N'BIG C', N'auto-en'),
(N'english', N'bic c', N'BIG C', N'auto-en'),
(N'english', N'bigc supercenter', N'BIG C', N'auto-en'),
(N'english', N'foodland', N'FOODLAND', N'auto-en'),
(N'english', N'food land', N'FOODLAND', N'auto-en'),
(N'english', N'foodland supermarket', N'FOODLAND', N'auto-en'),
(N'english', N'lotus', N'LOTUS', N'auto-en'),
(N'english', N'lotuss', N'LOTUS', N'auto-en'),
(N'english', N'lotus''s', N'LOTUS', N'auto-en'),
(N'english', N'tesco lotus', N'LOTUS', N'auto-en'),
(N'english', N'tesco', N'LOTUS', N'auto-en'),
(N'english', N'makro', N'MAKRO', N'auto-en'),
(N'english', N'macro', N'MAKRO', N'auto-en'),
(N'english', N'makro store', N'MAKRO', N'auto-en'),
(N'english', N'siam makro', N'MAKRO', N'auto-en'),
(N'english', N'max valu', N'MAX VALU', N'auto-en'),
(N'english', N'maxvalu', N'MAX VALU', N'auto-en'),
(N'english', N'maxvalue', N'MAX VALU', N'auto-en'),
(N'english', N'max value', N'MAX VALU', N'auto-en'),
(N'english', N'the mall', N'The Mall', N'auto-en'),
(N'english', N'themall', N'The Mall', N'auto-en'),
(N'english', N'the mall department store', N'The Mall', N'auto-en'),
(N'english', N'tops', N'TOPS', N'auto-en'),
(N'english', N'top', N'TOPS', N'auto-en'),
(N'english', N'tops market', N'TOPS', N'auto-en'),
(N'english', N'tops supermarket', N'TOPS', N'auto-en'),
(N'english', N'tops daily', N'TOPS', N'auto-en'),
(N'english', N'villa', N'Villa', N'auto-en'),
(N'english', N'villa market', N'Villa', N'auto-en'),
(N'english', N'villamarket', N'Villa', N'auto-en'),
(N'english', N'cj express', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'cjexpress', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'cj', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'cj express group', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'cj more', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'cjmore', N'บริษัท ซี.เจ. เอ็กซ์เพรส กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'central food', N'บริษัท เซ็นทรัล ฟู้ด โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'central food wholesale', N'บริษัท เซ็นทรัล ฟู้ด โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'centralfood', N'บริษัท เซ็นทรัล ฟู้ด โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'central food holesale', N'บริษัท เซ็นทรัล ฟู้ด โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'central', N'บริษัท เซ็นทรัล ฟู้ด โฮลเซลล์ จำกัด', N'auto-en'),
(N'english', N'ufm fuji', N'UFM ฟูจิ', N'auto-en'),
(N'english', N'ufm', N'UFM ฟูจิ', N'auto-en'),
(N'english', N'fuji', N'UFM ฟูจิ', N'auto-en'),
(N'english', N'ufmfuji', N'UFM ฟูจิ', N'auto-en'),
(N'english', N'ufm fuji super', N'UFM ฟูจิ', N'auto-en'),
(N'english', N'chip heng', N'จิบเฮง', N'auto-en'),
(N'english', N'chipheng', N'จิบเฮง', N'auto-en'),
(N'english', N'jib heng', N'จิบเฮง', N'auto-en'),
(N'english', N'jibheng', N'จิบเฮง', N'auto-en'),
(N'english', N'chibheng', N'จิบเฮง', N'auto-en'),
(N'english', N'kornchai sahapat', N'บริษัท กรชัยสหพัฒน จำกัด', N'auto-en'),
(N'english', N'kornchai', N'บริษัท กรชัยสหพัฒน จำกัด', N'auto-en'),
(N'english', N'konchai sahapat', N'บริษัท กรชัยสหพัฒน จำกัด', N'auto-en'),
(N'english', N'kornchaisahapat', N'บริษัท กรชัยสหพัฒน จำกัด', N'auto-en'),
(N'english', N'korn chai', N'บริษัท กรชัยสหพัฒน จำกัด', N'auto-en'),
(N'english', N'kiatsin wholesale', N'บริษัท เกียรติสินโฮลเซล จำกัด', N'auto-en'),
(N'english', N'kiatsin', N'บริษัท เกียรติสินโฮลเซล จำกัด', N'auto-en'),
(N'english', N'kiatsin holsell', N'บริษัท เกียรติสินโฮลเซล จำกัด', N'auto-en'),
(N'english', N'kiat sin', N'บริษัท เกียรติสินโฮลเซล จำกัด', N'auto-en'),
(N'english', N'kiattisin', N'บริษัท เกียรติสินโฮลเซล จำกัด', N'auto-en'),
(N'english', N'k and t', N'บริษัท เค แอนด์ ที', N'auto-en'),
(N'english', N'k & t', N'บริษัท เค แอนด์ ที', N'auto-en'),
(N'english', N'k&t', N'บริษัท เค แอนด์ ที', N'auto-en'),
(N'english', N'kandt', N'บริษัท เค แอนด์ ที', N'auto-en'),
(N'english', N'kt', N'บริษัท เค แอนด์ ที', N'auto-en'),
(N'english', N'jamfah savemart', N'บริษัท แจ่มฟ้า เซฟมาร์ท จำกัด', N'auto-en'),
(N'english', N'jamfa savemart', N'บริษัท แจ่มฟ้า เซฟมาร์ท จำกัด', N'auto-en'),
(N'english', N'jaemfa savemart', N'บริษัท แจ่มฟ้า เซฟมาร์ท จำกัด', N'auto-en'),
(N'english', N'jamfah', N'บริษัท แจ่มฟ้า เซฟมาร์ท จำกัด', N'auto-en'),
(N'english', N'jamfah save mart', N'บริษัท แจ่มฟ้า เซฟมาร์ท จำกัด', N'auto-en'),
(N'english', N'yong sanguan', N'บริษัท ยงสงวนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yongsanguan', N'บริษัท ยงสงวนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yong sanguan group', N'บริษัท ยงสงวนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yongsanguan group', N'บริษัท ยงสงวนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yong sa nguan', N'บริษัท ยงสงวนกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'rattanapaiboon', N'บริษัท รัตนไพบูลย์ สมุทรสงคราม 2555', N'auto-en'),
(N'english', N'rattana paiboon', N'บริษัท รัตนไพบูลย์ สมุทรสงคราม 2555', N'auto-en'),
(N'english', N'rattanapaiboon samut songkhram', N'บริษัท รัตนไพบูลย์ สมุทรสงคราม 2555', N'auto-en'),
(N'english', N'rattanapiboon', N'บริษัท รัตนไพบูลย์ สมุทรสงคราม 2555', N'auto-en'),
(N'english', N'ratanapaiboon', N'บริษัท รัตนไพบูลย์ สมุทรสงคราม 2555', N'auto-en'),
(N'english', N'lim nam heng', N'บริษัท ลิ้มน่ำเฮง จำกัด', N'auto-en'),
(N'english', N'limnamheng', N'บริษัท ลิ้มน่ำเฮง จำกัด', N'auto-en'),
(N'english', N'lim namheng', N'บริษัท ลิ้มน่ำเฮง จำกัด', N'auto-en'),
(N'english', N'lim nam heng', N'บริษัท ลิ้มน่ำเฮง จำกัด', N'auto-en'),
(N'english', N'limnam heng', N'บริษัท ลิ้มน่ำเฮง จำกัด', N'auto-en'),
(N'english', N'watthananukit', N'บริษัท วัฒนานุกิจ จำกัด', N'auto-en'),
(N'english', N'wattananukit', N'บริษัท วัฒนานุกิจ จำกัด', N'auto-en'),
(N'english', N'wattana nukit', N'บริษัท วัฒนานุกิจ จำกัด', N'auto-en'),
(N'english', N'watthananukich', N'บริษัท วัฒนานุกิจ จำกัด', N'auto-en'),
(N'english', N'wathananukit', N'บริษัท วัฒนานุกิจ จำกัด', N'auto-en'),
(N'english', N'win cosmetics', N'บริษัท วิน คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'win cosmetic', N'บริษัท วิน คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'wincosmetics', N'บริษัท วิน คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'win cosme', N'บริษัท วิน คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'wincosmetic', N'บริษัท วิน คอสเมติคส์ จำกัด', N'auto-en'),
(N'english', N'econ warehouse', N'บริษัท อีคอนแวร์เฮ้าส์ จำกัด', N'auto-en'),
(N'english', N'econwarehouse', N'บริษัท อีคอนแวร์เฮ้าส์ จำกัด', N'auto-en'),
(N'english', N'econ ware house', N'บริษัท อีคอนแวร์เฮ้าส์ จำกัด', N'auto-en'),
(N'english', N'econwarehouse', N'บริษัท อีคอนแวร์เฮ้าส์ จำกัด', N'auto-en'),
(N'english', N'econ', N'บริษัท อีคอนแวร์เฮ้าส์ จำกัด', N'auto-en'),
(N'english', N'jongkol 1999', N'ห้างหุ้นส่วนจำกัด จงกล 1999', N'auto-en'),
(N'english', N'jongkol1999', N'ห้างหุ้นส่วนจำกัด จงกล 1999', N'auto-en'),
(N'english', N'jongkol', N'ห้างหุ้นส่วนจำกัด จงกล 1999', N'auto-en'),
(N'english', N'chongkol 1999', N'ห้างหุ้นส่วนจำกัด จงกล 1999', N'auto-en'),
(N'english', N'chongkon 1999', N'ห้างหุ้นส่วนจำกัด จงกล 1999', N'auto-en'),
(N'english', N'chok watcharin', N'ห้างหุ้นส่วนจำกัด โชควัชริน', N'auto-en'),
(N'english', N'chokwatcharin', N'ห้างหุ้นส่วนจำกัด โชควัชริน', N'auto-en'),
(N'english', N'chok wacharin', N'ห้างหุ้นส่วนจำกัด โชควัชริน', N'auto-en'),
(N'english', N'chokwatcharin', N'ห้างหุ้นส่วนจำกัด โชควัชริน', N'auto-en'),
(N'english', N'chok watcharin', N'ห้างหุ้นส่วนจำกัด โชควัชริน', N'auto-en'),
(N'english', N'talad mai jumjim', N'ห้างหุ้นส่วนจำกัด ตลาดใหม่ จุ๋มจิ๋ม', N'auto-en'),
(N'english', N'taladmai jumjim', N'ห้างหุ้นส่วนจำกัด ตลาดใหม่ จุ๋มจิ๋ม', N'auto-en'),
(N'english', N'jumjim', N'ห้างหุ้นส่วนจำกัด ตลาดใหม่ จุ๋มจิ๋ม', N'auto-en'),
(N'english', N'talat mai chumchim', N'ห้างหุ้นส่วนจำกัด ตลาดใหม่ จุ๋มจิ๋ม', N'auto-en'),
(N'english', N'talad mai chumchim', N'ห้างหุ้นส่วนจำกัด ตลาดใหม่ จุ๋มจิ๋ม', N'auto-en'),
(N'english', N'big kim', N'ห้างหุ้นส่วนจำกัด บิ๊กกิม', N'auto-en'),
(N'english', N'bigkim', N'ห้างหุ้นส่วนจำกัด บิ๊กกิม', N'auto-en'),
(N'english', N'bik kim', N'ห้างหุ้นส่วนจำกัด บิ๊กกิม', N'auto-en'),
(N'english', N'big gim', N'ห้างหุ้นส่วนจำกัด บิ๊กกิม', N'auto-en'),
(N'english', N'bigkimm', N'ห้างหุ้นส่วนจำกัด บิ๊กกิม', N'auto-en'),
(N'english', N'fairy supermart', N'ห้างหุ้นส่วนจำกัด แฟรี่ ซุปเปอร์มาร์ท', N'auto-en'),
(N'english', N'fairy super mart', N'ห้างหุ้นส่วนจำกัด แฟรี่ ซุปเปอร์มาร์ท', N'auto-en'),
(N'english', N'fairy', N'ห้างหุ้นส่วนจำกัด แฟรี่ ซุปเปอร์มาร์ท', N'auto-en'),
(N'english', N'fairysupermart', N'ห้างหุ้นส่วนจำกัด แฟรี่ ซุปเปอร์มาร์ท', N'auto-en'),
(N'english', N'fairy supermarket', N'ห้างหุ้นส่วนจำกัด แฟรี่ ซุปเปอร์มาร์ท', N'auto-en'),
(N'english', N'yala sanguan', N'ห้างหุ้นส่วนจำกัด ยะลาสงวนการค้า', N'auto-en'),
(N'english', N'yala sanguan kanka', N'ห้างหุ้นส่วนจำกัด ยะลาสงวนการค้า', N'auto-en'),
(N'english', N'yalasanguan', N'ห้างหุ้นส่วนจำกัด ยะลาสงวนการค้า', N'auto-en'),
(N'english', N'yala sa nguan', N'ห้างหุ้นส่วนจำกัด ยะลาสงวนการค้า', N'auto-en'),
(N'english', N'yala sanguan trade', N'ห้างหุ้นส่วนจำกัด ยะลาสงวนการค้า', N'auto-en'),
(N'english', N'lee wiwat thawon', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร', N'auto-en'),
(N'english', N'leewiwat', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร', N'auto-en'),
(N'english', N'lee wiwat', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร', N'auto-en'),
(N'english', N'leewiwatthawon', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร', N'auto-en'),
(N'english', N'lee wiwat thaworn', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร', N'auto-en'),
(N'english', N'sirirat roi et', N'ห้างหุ้นส่วนจำกัด ศิริรัตน์ร้อยเอ็ด', N'auto-en'),
(N'english', N'sirirat roiet', N'ห้างหุ้นส่วนจำกัด ศิริรัตน์ร้อยเอ็ด', N'auto-en'),
(N'english', N'siriratroiet', N'ห้างหุ้นส่วนจำกัด ศิริรัตน์ร้อยเอ็ด', N'auto-en'),
(N'english', N'sirirat', N'ห้างหุ้นส่วนจำกัด ศิริรัตน์ร้อยเอ็ด', N'auto-en'),
(N'english', N'sirirat roi-et', N'ห้างหุ้นส่วนจำกัด ศิริรัตน์ร้อยเอ็ด', N'auto-en'),
(N'english', N'charoenphan', N'ห้างหุ้นส่วนจำกัด เจริญภัณฑ์', N'auto-en'),
(N'english', N'charoen phan', N'ห้างหุ้นส่วนจำกัด เจริญภัณฑ์', N'auto-en'),
(N'english', N'charoenpan', N'ห้างหุ้นส่วนจำกัด เจริญภัณฑ์', N'auto-en'),
(N'english', N'charoenphand', N'ห้างหุ้นส่วนจำกัด เจริญภัณฑ์', N'auto-en'),
(N'english', N'jaroenphan', N'ห้างหุ้นส่วนจำกัด เจริญภัณฑ์', N'auto-en'),
(N'english', N'chaiyaporn eawhuad 1992', N'ห้างหุ้นส่วนจำกัด ชัยพร เอี้ยวฮวด 1992', N'auto-en'),
(N'english', N'chaiyaporn', N'ห้างหุ้นส่วนจำกัด ชัยพร เอี้ยวฮวด 1992', N'auto-en'),
(N'english', N'chaiporn eawhuad', N'ห้างหุ้นส่วนจำกัด ชัยพร เอี้ยวฮวด 1992', N'auto-en'),
(N'english', N'chaiyaporn eaw huad 1992', N'ห้างหุ้นส่วนจำกัด ชัยพร เอี้ยวฮวด 1992', N'auto-en'),
(N'english', N'chaiyaporn iewhuad', N'ห้างหุ้นส่วนจำกัด ชัยพร เอี้ยวฮวด 1992', N'auto-en'),
(N'english', N'chok charoensin', N'ห้างหุ้นส่วนจำกัด โชคเจริญสิน', N'auto-en'),
(N'english', N'chokcharoensin', N'ห้างหุ้นส่วนจำกัด โชคเจริญสิน', N'auto-en'),
(N'english', N'chok jaroensin', N'ห้างหุ้นส่วนจำกัด โชคเจริญสิน', N'auto-en'),
(N'english', N'chokcharoen sin', N'ห้างหุ้นส่วนจำกัด โชคเจริญสิน', N'auto-en'),
(N'english', N'chok charoen sin', N'ห้างหุ้นส่วนจำกัด โชคเจริญสิน', N'auto-en'),
(N'english', N'chaichana superstore', N'ห้างหุ้นส่วนจำกัด ไชยชนะ ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'chaichana super store', N'ห้างหุ้นส่วนจำกัด ไชยชนะ ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'chaichana', N'ห้างหุ้นส่วนจำกัด ไชยชนะ ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'chaichanasuperstore', N'ห้างหุ้นส่วนจำกัด ไชยชนะ ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'chaichana super', N'ห้างหุ้นส่วนจำกัด ไชยชนะ ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'chaisaeng', N'ห้างหุ้นส่วนจำกัด ไชยแสง', N'auto-en'),
(N'english', N'chai saeng', N'ห้างหุ้นส่วนจำกัด ไชยแสง', N'auto-en'),
(N'english', N'chaisang', N'ห้างหุ้นส่วนจำกัด ไชยแสง', N'auto-en'),
(N'english', N'chaiseng', N'ห้างหุ้นส่วนจำกัด ไชยแสง', N'auto-en'),
(N'english', N'chaysaeng', N'ห้างหุ้นส่วนจำกัด ไชยแสง', N'auto-en'),
(N'english', N'tongho', N'ห้างหุ้นส่วนจำกัด ตงโห', N'auto-en'),
(N'english', N'tong ho', N'ห้างหุ้นส่วนจำกัด ตงโห', N'auto-en'),
(N'english', N'tonghoh', N'ห้างหุ้นส่วนจำกัด ตงโห', N'auto-en'),
(N'english', N'dongho', N'ห้างหุ้นส่วนจำกัด ตงโห', N'auto-en'),
(N'english', N'tong hoe', N'ห้างหุ้นส่วนจำกัด ตงโห', N'auto-en'),
(N'english', N'thung song yong charoen', N'ห้างหุ้นส่วนจำกัด ทุ่งสงยงเจริญ', N'auto-en'),
(N'english', N'thungsong yongcharoen', N'ห้างหุ้นส่วนจำกัด ทุ่งสงยงเจริญ', N'auto-en'),
(N'english', N'thungsongyongcharoen', N'ห้างหุ้นส่วนจำกัด ทุ่งสงยงเจริญ', N'auto-en'),
(N'english', N'tung song yong charoen', N'ห้างหุ้นส่วนจำกัด ทุ่งสงยงเจริญ', N'auto-en'),
(N'english', N'thung song yongjaroen', N'ห้างหุ้นส่วนจำกัด ทุ่งสงยงเจริญ', N'auto-en'),
(N'english', N'narapanich', N'ห้างหุ้นส่วนจำกัด นราพาณิชย์', N'auto-en'),
(N'english', N'nara panich', N'ห้างหุ้นส่วนจำกัด นราพาณิชย์', N'auto-en'),
(N'english', N'narapanit', N'ห้างหุ้นส่วนจำกัด นราพาณิชย์', N'auto-en'),
(N'english', N'narapanichaya', N'ห้างหุ้นส่วนจำกัด นราพาณิชย์', N'auto-en'),
(N'english', N'nara phanit', N'ห้างหุ้นส่วนจำกัด นราพาณิชย์', N'auto-en'),
(N'english', N'new kan eng', N'ห้างหุ้นส่วนจำกัด นิวกันเอง', N'auto-en'),
(N'english', N'newkaneng', N'ห้างหุ้นส่วนจำกัด นิวกันเอง', N'auto-en'),
(N'english', N'new kaneng', N'ห้างหุ้นส่วนจำกัด นิวกันเอง', N'auto-en'),
(N'english', N'niew kan eng', N'ห้างหุ้นส่วนจำกัด นิวกันเอง', N'auto-en'),
(N'english', N'new gun eng', N'ห้างหุ้นส่วนจำกัด นิวกันเอง', N'auto-en'),
(N'english', N'bunsiri fang', N'ห้างหุ้นส่วนจำกัด บุญศิริฝาง', N'auto-en'),
(N'english', N'boonsiri fang', N'ห้างหุ้นส่วนจำกัด บุญศิริฝาง', N'auto-en'),
(N'english', N'boonsirifang', N'ห้างหุ้นส่วนจำกัด บุญศิริฝาง', N'auto-en'),
(N'english', N'bunsirifang', N'ห้างหุ้นส่วนจำกัด บุญศิริฝาง', N'auto-en'),
(N'english', N'boon siri fang', N'ห้างหุ้นส่วนจำกัด บุญศิริฝาง', N'auto-en'),
(N'english', N'ploy super', N'ห้างหุ้นส่วนจำกัด พลอยซุปเปอร์', N'auto-en'),
(N'english', N'ploysuper', N'ห้างหุ้นส่วนจำกัด พลอยซุปเปอร์', N'auto-en'),
(N'english', N'ploy supper', N'ห้างหุ้นส่วนจำกัด พลอยซุปเปอร์', N'auto-en'),
(N'english', N'phloi super', N'ห้างหุ้นส่วนจำกัด พลอยซุปเปอร์', N'auto-en'),
(N'english', N'ploy', N'ห้างหุ้นส่วนจำกัด พลอยซุปเปอร์', N'auto-en'),
(N'english', N'phithun super', N'ห้างหุ้นส่วนจำกัด พิทูนซุปเปอร์', N'auto-en'),
(N'english', N'pithun super', N'ห้างหุ้นส่วนจำกัด พิทูนซุปเปอร์', N'auto-en'),
(N'english', N'phithunsuper', N'ห้างหุ้นส่วนจำกัด พิทูนซุปเปอร์', N'auto-en'),
(N'english', N'pitoon super', N'ห้างหุ้นส่วนจำกัด พิทูนซุปเปอร์', N'auto-en'),
(N'english', N'phitoon super', N'ห้างหุ้นส่วนจำกัด พิทูนซุปเปอร์', N'auto-en'),
(N'english', N'navy marine', N'กิจการร้านค้าและการบริการนาวิกโยธิน', N'auto-en'),
(N'english', N'marine corps store', N'กิจการร้านค้าและการบริการนาวิกโยธิน', N'auto-en'),
(N'english', N'navikayothin', N'กิจการร้านค้าและการบริการนาวิกโยธิน', N'auto-en'),
(N'english', N'kitchakan navy', N'กิจการร้านค้าและการบริการนาวิกโยธิน', N'auto-en'),
(N'english', N'navy welfare store', N'กิจการร้านค้าและการบริการนาวิกโยธิน', N'auto-en'),
(N'english', N'welfare store', N'กิจการร้านค้าสวัสดิการภายใน', N'auto-en'),
(N'english', N'internal welfare', N'กิจการร้านค้าสวัสดิการภายใน', N'auto-en'),
(N'english', N'sawatdikan', N'กิจการร้านค้าสวัสดิการภายใน', N'auto-en'),
(N'english', N'staff welfare shop', N'กิจการร้านค้าสวัสดิการภายใน', N'auto-en'),
(N'english', N'welfare shop', N'กิจการร้านค้าสวัสดิการภายใน', N'auto-en'),
(N'english', N'jintai junior', N'จินไถ่ จูเนียร์', N'auto-en'),
(N'english', N'jin tai junior', N'จินไถ่ จูเนียร์', N'auto-en'),
(N'english', N'jintaijunior', N'จินไถ่ จูเนียร์', N'auto-en'),
(N'english', N'chintai junior', N'จินไถ่ จูเนียร์', N'auto-en'),
(N'english', N'junior', N'จินไถ่ จูเนียร์', N'auto-en'),
(N'english', N'chiangmai direct', N'เชียงใหม่ ไดเร็คท์', N'auto-en'),
(N'english', N'chiang mai direct', N'เชียงใหม่ ไดเร็คท์', N'auto-en'),
(N'english', N'chiangmaidirect', N'เชียงใหม่ ไดเร็คท์', N'auto-en'),
(N'english', N'cm direct', N'เชียงใหม่ ไดเร็คท์', N'auto-en'),
(N'english', N'chiangmai', N'เชียงใหม่ ไดเร็คท์', N'auto-en'),
(N'english', N'tae hok seng', N'แต้ฮกเซ้ง', N'auto-en'),
(N'english', N'taehokseng', N'แต้ฮกเซ้ง', N'auto-en'),
(N'english', N'tea hok seng', N'แต้ฮกเซ้ง', N'auto-en'),
(N'english', N'taehok seng', N'แต้ฮกเซ้ง', N'auto-en'),
(N'english', N'kanokkan department store', N'บริษัท กนกกาญจน์ดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'kanokkan', N'บริษัท กนกกาญจน์ดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'kanok kan department store', N'บริษัท กนกกาญจน์ดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'kanokkanchan department store', N'บริษัท กนกกาญจน์ดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'kanokkan store', N'บริษัท กนกกาญจน์ดีพาร์ทเม้นท์สโตร์', N'auto-en'),
(N'english', N'kalasin plaza', N'บริษัท กาฬสินธุ์ พลาซ่า จำกัด', N'auto-en'),
(N'english', N'kalasinplaza', N'บริษัท กาฬสินธุ์ พลาซ่า จำกัด', N'auto-en'),
(N'english', N'kalasin', N'บริษัท กาฬสินธุ์ พลาซ่า จำกัด', N'auto-en'),
(N'english', N'galasin plaza', N'บริษัท กาฬสินธุ์ พลาซ่า จำกัด', N'auto-en'),
(N'english', N'kalasin plaza co', N'บริษัท กาฬสินธุ์ พลาซ่า จำกัด', N'auto-en'),
(N'english', N'kammachian wholesale', N'บริษัท กำมะเชียรค้าส่ง จำกัด', N'auto-en'),
(N'english', N'kammachian', N'บริษัท กำมะเชียรค้าส่ง จำกัด', N'auto-en'),
(N'english', N'kammachian khasong', N'บริษัท กำมะเชียรค้าส่ง จำกัด', N'auto-en'),
(N'english', N'kammachiar wholesale', N'บริษัท กำมะเชียรค้าส่ง จำกัด', N'auto-en'),
(N'english', N'kammachian ka song', N'บริษัท กำมะเชียรค้าส่ง จำกัด', N'auto-en'),
(N'english', N'goods store', N'บริษัท กู๊ดส์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'goods', N'บริษัท กู๊ดส์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'goodsstore', N'บริษัท กู๊ดส์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'good store', N'บริษัท กู๊ดส์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'goods store co', N'บริษัท กู๊ดส์ สโตร์ จำกัด', N'auto-en'),
(N'english', N'khemthong superstore', N'บริษัท เข็มทองซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'khemthong super store', N'บริษัท เข็มทองซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'khemthong', N'บริษัท เข็มทองซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'khemthongsuperstore', N'บริษัท เข็มทองซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'khem thong superstore', N'บริษัท เข็มทองซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'quality drug', N'บริษัท ควอลิตี้ดรัก จำกัด', N'auto-en'),
(N'english', N'qualitydrug', N'บริษัท ควอลิตี้ดรัก จำกัด', N'auto-en'),
(N'english', N'quality drugs', N'บริษัท ควอลิตี้ดรัก จำกัด', N'auto-en'),
(N'english', N'quality', N'บริษัท ควอลิตี้ดรัก จำกัด', N'auto-en'),
(N'english', N'quality drug co', N'บริษัท ควอลิตี้ดรัก จำกัด', N'auto-en'),
(N'english', N'khubun supercenter', N'บริษัท คู่บุญซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'khubun super center', N'บริษัท คู่บุญซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'khubun', N'บริษัท คู่บุญซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'khu bun supercenter', N'บริษัท คู่บุญซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'khubunsupercenter', N'บริษัท คู่บุญซุปเปอร์เซ็นเตอร์ จำกัด', N'auto-en'),
(N'english', N'k&k superstore', N'บริษัท เคแอนด์เค ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'k and k superstore', N'บริษัท เคแอนด์เค ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'kk superstore', N'บริษัท เคแอนด์เค ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'k&k super store', N'บริษัท เคแอนด์เค ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'kandk superstore', N'บริษัท เคแอนด์เค ซุปเปอร์สโตร์', N'auto-en'),
(N'english', N'kosit store', N'บริษัท โฆษิตสโตร์ จำกัด', N'auto-en'),
(N'english', N'kositstore', N'บริษัท โฆษิตสโตร์ จำกัด', N'auto-en'),
(N'english', N'kosit', N'บริษัท โฆษิตสโตร์ จำกัด', N'auto-en'),
(N'english', N'khosit store', N'บริษัท โฆษิตสโตร์ จำกัด', N'auto-en'),
(N'english', N'kosit store co', N'บริษัท โฆษิตสโตร์ จำกัด', N'auto-en'),
(N'english', N'jephon super', N'บริษัท เจ้พร ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'je phon super', N'บริษัท เจ้พร ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'jaephon super', N'บริษัท เจ้พร ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'jephon', N'บริษัท เจ้พร ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'je phorn super', N'บริษัท เจ้พร ซุปเปอร์ จำกัด', N'auto-en'),
(N'english', N'merry group', N'บริษัท เมอร์รี่กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'merrygroup', N'บริษัท เมอร์รี่กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'merry', N'บริษัท เมอร์รี่กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'merri group', N'บริษัท เมอร์รี่กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'merry group co', N'บริษัท เมอร์รี่กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yutitham group', N'บริษัท ยุติธรรม กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yutithamgroup', N'บริษัท ยุติธรรม กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yutitham', N'บริษัท ยุติธรรม กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yuttitham group', N'บริษัท ยุติธรรม กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'yutithum group', N'บริษัท ยุติธรรม กรุ๊ป จำกัด', N'auto-en'),
(N'english', N'rop banchoet', N'บริษัท รอบบรรเจิด จำกัด', N'auto-en'),
(N'english', N'ropbanchoet', N'บริษัท รอบบรรเจิด จำกัด', N'auto-en'),
(N'english', N'rob banjerd', N'บริษัท รอบบรรเจิด จำกัด', N'auto-en'),
(N'english', N'rop banchaoet', N'บริษัท รอบบรรเจิด จำกัด', N'auto-en'),
(N'english', N'rob banchoet', N'บริษัท รอบบรรเจิด จำกัด', N'auto-en'),
(N'english', N'roi et hypermart', N'บริษัท ร้อยเอ็ดไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'roiet hypermart', N'บริษัท ร้อยเอ็ดไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'roi-et hypermart', N'บริษัท ร้อยเอ็ดไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'roiethypermart', N'บริษัท ร้อยเอ็ดไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'roi et hyper mart', N'บริษัท ร้อยเอ็ดไฮเปอร์มาร์ท จำกัด', N'auto-en'),
(N'english', N'london wholesale', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'london wholesale supermarket', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'londonwholesale', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'london', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'london holesale', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'londonholesale', N'บริษัท ลอนดอนโฮลเซล-ซูเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'lucky one', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'luckyone', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'lucky one 2560', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'lucky-one', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'lucky 1', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'lucky one 2017', N'บริษัท ลัคกี้-วัน 2560 จำกัด', N'auto-en'),
(N'english', N'lampang seri group', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'lampang seri', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'lampangseri', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'lampang seree group', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'lampang serikrup', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'lampang serigroup', N'บริษัท ลำปางเสรีกรุ๊ป จำกัด', N'auto-en'),
(N'english', N'leng yai wholesale', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'leng yai', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'lengyai', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'leng yai holesales', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'leng yai wholesales', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'leng yai holsale', N'บริษัท เล้ง ใหญ่ โฮลเซลส์ จำกัด นายเรืองวิทย์ บริสุทธิ์บงกช', N'auto-en'),
(N'english', N'wannakitcharoen', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'wannakit charoen', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'wannakijcharoen', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'wannakit', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'wannakitjaroen', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'wannakitcharoen 2000', N'บริษัท วรรณกิจเจริญ (2000) จำกัด', N'auto-en'),
(N'english', N'watcharawan', N'บริษัท วัชราวรรณ(2008) จำกัด', N'auto-en'),
(N'english', N'watcharawan 2008', N'บริษัท วัชราวรรณ(2008) จำกัด', N'auto-en'),
(N'english', N'wacharawan', N'บริษัท วัชราวรรณ(2008) จำกัด', N'auto-en'),
(N'english', N'vatcharawan', N'บริษัท วัชราวรรณ(2008) จำกัด', N'auto-en'),
(N'english', N'variety superstore', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'varietysuperstore', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'variety super store', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'variety', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'variety superstor', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'varaity superstore', N'บริษัท วาไรตี้ซุปเปอร์สโตร์ จำกัด', N'auto-en'),
(N'english', N'withithep', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'withi thep', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'wuthithep', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'vithithep', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'withithep department store', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'withithep sapphasinkha', N'บริษัท วิถีเทพสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'witthayaphan super', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'witthayaphan', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'wittayaphan super', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'wittayaphan', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'witayapan super', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'witthayapan', N'บริษัท วิทยาภัณฑ์ ซูเปอร์ จำกัด', N'auto-en'),
(N'english', N'rian thong super big', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'rianthong superbig', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'rian thong superbig', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'rianthong', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'rean thong super big', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'riantong superbig', N'บริษัท เหรียญทอง ซุปเปอร์บิ๊ก จำกัด', N'auto-en'),
(N'english', N'mai commercial', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'maicommercial', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'mai commercials', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'new commercial', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'mai com', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'mai commercia', N'บริษัท ใหม่ คอมเมอร์เชียล จำกัด', N'auto-en'),
(N'english', N'amphon', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'amporn', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'amphon department store', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'amporn sapphasinkha', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'ampornsapphasinkha', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'amphorn', N'บริษัท อัมพรสรรพสินค้า จำกัด', N'auto-en'),
(N'english', N'kirati store', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'kirati', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'kiratistore', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'keerati store', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'keerati', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'kirati sto', N'ห้างหุ้นส่วนจำกัด กีรติ สโตร์', N'auto-en'),
(N'english', N'khong kan kha', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'khongkankha', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'kong kan ka', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'khongkanka', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'khong kankha', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'kongkanka', N'ห้างหุ้นส่วนจำกัด คงการค้า', N'auto-en'),
(N'english', N'phuket grocery', N'ห้างหุ้นส่วนจำกัด ภูเก็ตโกรเซอรี่', N'auto-en'),
(N'english', N'phuketgrocery', N'ห้างหุ้นส่วนจำกัด ภูเก็ตโกรเซอรี่', N'auto-en'),
(N'english', N'phuket grocerie', N'ห้างหุ้นส่วนจำกัด ภูเก็ตโกรเซอรี่', N'auto-en'),
(N'english', N'puket grocery', N'ห้างหุ้นส่วนจำกัด ภูเก็ตโกรเซอรี่', N'auto-en'),
(N'english', N'phuket grosery', N'ห้างหุ้นส่วนจำกัด ภูเก็ตโกรเซอรี่', N'auto-en'),
(N'english', N'mukdahan banchuen', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'mukdahanbanchuen', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'mukdahan ban chuen', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'mukdahan', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'mukdahan banchun', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'mukdahan banchuern', N'ห้างหุ้นส่วนจำกัด มุกดาหารบานชื่น', N'auto-en'),
(N'english', N'yala mueang mai', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'yala muang mai', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'yalamuangmai', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'yala mueangmai', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'yala new town', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'yala muengmai', N'ห้างหุ้นส่วนจำกัด ยะลาเมืองใหม่', N'auto-en'),
(N'english', N'ying yai', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'yingyai', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'ying yai store', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'yingyai store', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'ying-yai', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'yong yai', N'ห้างหุ้นส่วนจำกัด ยิ่งใหญ่', N'auto-en'),
(N'english', N'rak thai supermarket', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'rakthai supermarket', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'rak thai', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'rakthai', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'rak thai super market', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'rakthaisupermarket', N'ห้างหุ้นส่วนจำกัด รักไทยซุปเปอร์มาร์เก็ต', N'auto-en'),
(N'english', N'lim kuang nguan', N'ห้างหุ้นส่วนจำกัด ลิ้มกวงง้วน', N'auto-en'),
(N'english', N'limkuangnguan', N'ห้างหุ้นส่วนจำกัด ลิ้มกวงง้วน', N'auto-en'),
(N'english', N'lim guang nguan', N'ห้างหุ้นส่วนจำกัด ลิ้มกวงง้วน', N'auto-en'),
(N'english', N'limkuang', N'ห้างหุ้นส่วนจำกัด ลิ้มกวงง้วน', N'auto-en'),
(N'english', N'lee mart express', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'leemart express', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'leemartexpress', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'lee mart', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'leewiwat thawon', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'lee wiwat', N'ห้างหุ้นส่วนจำกัด ลีวิวัฒน์ถาวร (ลีมาร์ทเอ็กซ์เพรส)', N'auto-en'),
(N'english', N'wanna pranee', N'ห้างหุ้นส่วนจำกัด วรรณาปราณี', N'auto-en'),
(N'english', N'wannapranee', N'ห้างหุ้นส่วนจำกัด วรรณาปราณี', N'auto-en'),
(N'english', N'wanna pranee store', N'ห้างหุ้นส่วนจำกัด วรรณาปราณี', N'auto-en'),
(N'english', N'wanna', N'ห้างหุ้นส่วนจำกัด วรรณาปราณี', N'auto-en'),
(N'english', N'wandee store', N'ห้างหุ้นส่วนจำกัด วันดีสโตร์', N'auto-en'),
(N'english', N'wandeestore', N'ห้างหุ้นส่วนจำกัด วันดีสโตร์', N'auto-en'),
(N'english', N'wandee', N'ห้างหุ้นส่วนจำกัด วันดีสโตร์', N'auto-en'),
(N'english', N'one day store', N'ห้างหุ้นส่วนจำกัด วันดีสโตร์', N'auto-en'),
(N'english', N'wan dee store', N'ห้างหุ้นส่วนจำกัด วันดีสโตร์', N'auto-en'),
(N'english', N's trimit', N'ห้างหุ้นส่วนจำกัด ส.ตรีมิตร', N'auto-en'),
(N'english', N'so trimit', N'ห้างหุ้นส่วนจำกัด ส.ตรีมิตร', N'auto-en'),
(N'english', N's.trimit', N'ห้างหุ้นส่วนจำกัด ส.ตรีมิตร', N'auto-en'),
(N'english', N'trimit', N'ห้างหุ้นส่วนจำกัด ส.ตรีมิตร', N'auto-en'),
(N'english', N's tri mit', N'ห้างหุ้นส่วนจำกัด ส.ตรีมิตร', N'auto-en'),
(N'english', N's thawi phan store', N'ห้างหุ้นส่วนจำกัด ส.ทวีภัณฑ์สโตร์', N'auto-en'),
(N'english', N'so thaweephan store', N'ห้างหุ้นส่วนจำกัด ส.ทวีภัณฑ์สโตร์', N'auto-en'),
(N'english', N's.thaweephan', N'ห้างหุ้นส่วนจำกัด ส.ทวีภัณฑ์สโตร์', N'auto-en'),
(N'english', N'thaweephan store', N'ห้างหุ้นส่วนจำกัด ส.ทวีภัณฑ์สโตร์', N'auto-en'),
(N'english', N's thawee phan', N'ห้างหุ้นส่วนจำกัด ส.ทวีภัณฑ์สโตร์', N'auto-en'),
(N'english', N'sahasin trading', N'ห้างหุ้นส่วนจำกัด สหสินเทรดดิ้ง', N'auto-en'),
(N'english', N'sahasintrading', N'ห้างหุ้นส่วนจำกัด สหสินเทรดดิ้ง', N'auto-en'),
(N'english', N'saha sin trading', N'ห้างหุ้นส่วนจำกัด สหสินเทรดดิ้ง', N'auto-en'),
(N'english', N'sahasin', N'ห้างหุ้นส่วนจำกัด สหสินเทรดดิ้ง', N'auto-en'),
(N'english', N'sukhothai sukkasem', N'ห้างหุ้นส่วนจำกัด สุโขทัยสุขเกษม', N'auto-en'),
(N'english', N'sukhothaisukkasem', N'ห้างหุ้นส่วนจำกัด สุโขทัยสุขเกษม', N'auto-en'),
(N'english', N'sukhothai suk kasem', N'ห้างหุ้นส่วนจำกัด สุโขทัยสุขเกษม', N'auto-en'),
(N'english', N'sukhothai', N'ห้างหุ้นส่วนจำกัด สุโขทัยสุขเกษม', N'auto-en'),
(N'english', N'suparat minimart', N'ห้างหุ้นส่วนจำกัด สุภารัตน์ มินิมาร', N'auto-en'),
(N'english', N'suparatminimart', N'ห้างหุ้นส่วนจำกัด สุภารัตน์ มินิมาร', N'auto-en'),
(N'english', N'supharat minimart', N'ห้างหุ้นส่วนจำกัด สุภารัตน์ มินิมาร', N'auto-en'),
(N'english', N'suparat minimar', N'ห้างหุ้นส่วนจำกัด สุภารัตน์ มินิมาร', N'auto-en'),
(N'english', N'suparat', N'ห้างหุ้นส่วนจำกัด สุภารัตน์ มินิมาร', N'auto-en'),
(N'english', N'saowanee big mart', N'ห้างหุ้นส่วนจำกัด เสาวนีย์ บิ๊กมาร์', N'auto-en'),
(N'english', N'saowaneebigmart', N'ห้างหุ้นส่วนจำกัด เสาวนีย์ บิ๊กมาร์', N'auto-en'),
(N'english', N'saowanee bigmar', N'ห้างหุ้นส่วนจำกัด เสาวนีย์ บิ๊กมาร์', N'auto-en'),
(N'english', N'saowanee big mar', N'ห้างหุ้นส่วนจำกัด เสาวนีย์ บิ๊กมาร์', N'auto-en'),
(N'english', N'saowanee', N'ห้างหุ้นส่วนจำกัด เสาวนีย์ บิ๊กมาร์', N'auto-en'),
(N'english', N'lam chok chai', N'ห้างหุ้นส่วนจำกัด หล่ำโชคชัย', N'auto-en'),
(N'english', N'lamchokchai', N'ห้างหุ้นส่วนจำกัด หล่ำโชคชัย', N'auto-en'),
(N'english', N'lam chokchai', N'ห้างหุ้นส่วนจำกัด หล่ำโชคชัย', N'auto-en'),
(N'english', N'lamchok', N'ห้างหุ้นส่วนจำกัด หล่ำโชคชัย', N'auto-en'),
(N'english', N'thai saeng thong', N'ห้างหุ้นส่วนจำกัด ห้างทองไทยแสงทอง', N'auto-en'),
(N'english', N'thaisaengthong', N'ห้างหุ้นส่วนจำกัด ห้างทองไทยแสงทอง', N'auto-en'),
(N'english', N'hang thong thai saeng thong', N'ห้างหุ้นส่วนจำกัด ห้างทองไทยแสงทอง', N'auto-en'),
(N'english', N'thai saengthong', N'ห้างหุ้นส่วนจำกัด ห้างทองไทยแสงทอง', N'auto-en'),
(N'english', N'thaisaeng thong', N'ห้างหุ้นส่วนจำกัด ห้างทองไทยแสงทอง', N'auto-en'),
(N'english', N'o asadang', N'ห้างหุ้นส่วนจำกัด อ.อัษฎางค์', N'auto-en'),
(N'english', N'or asadang', N'ห้างหุ้นส่วนจำกัด อ.อัษฎางค์', N'auto-en'),
(N'english', N'a.asadang', N'ห้างหุ้นส่วนจำกัด อ.อัษฎางค์', N'auto-en'),
(N'english', N'asadang', N'ห้างหุ้นส่วนจำกัด อ.อัษฎางค์', N'auto-en'),
(N'english', N'o asdang', N'ห้างหุ้นส่วนจำกัด อ.อัษฎางค์', N'auto-en'),
(N'english', N'hong long minimart', N'ห้างหุ้นส่วนจำกัด ฮงล้งมินิมาร์ท', N'auto-en'),
(N'english', N'honglongminimart', N'ห้างหุ้นส่วนจำกัด ฮงล้งมินิมาร์ท', N'auto-en'),
(N'english', N'hong long mini mart', N'ห้างหุ้นส่วนจำกัด ฮงล้งมินิมาร์ท', N'auto-en'),
(N'english', N'honglong minimart', N'ห้างหุ้นส่วนจำกัด ฮงล้งมินิมาร์ท', N'auto-en'),
(N'english', N'hong long', N'ห้างหุ้นส่วนจำกัด ฮงล้งมินิมาร์ท', N'auto-en'),
(N'english', N'hol mart retail', N'ห้างหุ้นส่วนจำกัด โฮลมาร์ท รีเทล', N'auto-en'),
(N'english', N'holmart retail', N'ห้างหุ้นส่วนจำกัด โฮลมาร์ท รีเทล', N'auto-en'),
(N'english', N'holmartretail', N'ห้างหุ้นส่วนจำกัด โฮลมาร์ท รีเทล', N'auto-en'),
(N'english', N'hol mart', N'ห้างหุ้นส่วนจำกัด โฮลมาร์ท รีเทล', N'auto-en'),
(N'english', N'whole mart retail', N'ห้างหุ้นส่วนจำกัด โฮลมาร์ท รีเทล', N'auto-en'),
(N'english', N'mai', N'ใหม่', N'auto-en'),
(N'english', N'new', N'ใหม่', N'auto-en'),
(N'english', N'andaman super', N'อันดามันซุปเปอร์', N'auto-en'),
(N'english', N'andamansuper', N'อันดามันซุปเปอร์', N'auto-en'),
(N'english', N'andaman supermarket', N'อันดามันซุปเปอร์', N'auto-en'),
(N'english', N'andaman', N'อันดามันซุปเปอร์', N'auto-en'),
(N'english', N'aew s store', N'แอว เอส สโตร์', N'auto-en'),
(N'english', N'aewsstore', N'แอว เอส สโตร์', N'auto-en'),
(N'english', N'aew es store', N'แอว เอส สโตร์', N'auto-en'),
(N'english', N'aew store', N'แอว เอส สโตร์', N'auto-en');
